[[headers]]
	for = "/*"
	[headers.values]
		Permissions-Policy = "browsing-topics=(), interest-cohort=(), join-ad-interest-group=(), run-ad-auction=()"

[[redirects]]
	from = "/projects"
	to = "/stacktrace"

[[redirects]]
	from = "/profile/naiyer"
	to = "/about"

[[redirects]]
	from = "/blog/:year/:month/:date/:slug"
	to = "/post/:year/:month/:date/:slug"

[[redirects]]
	from = "/blog"
	to = "/posts"

[[redirects]]
	from = "/blog/1"
	to = "/posts/1"

[[redirects]]
	from = "/blog/2"
	to = "/posts/2"

[[redirects]]
	from = "/blog/3"
	to = "/posts/3"

[[redirects]]
	from = "/blog/4"
	to = "/posts/4"
