name: deploy

on:
  push:
    branches:
      - main

env:
  # speed up the build by stopping wrangler action from downloading useless browser binaries
  PUPPETEER_SKIP_DOWNLOAD: true
  ASTRO_TELEMETRY_DISABLED: 1
  WRANGLER_SEND_METRICS: false
  # see https://github.com/pnpm/setup/issues/10
  CI: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Setup PNPM
        uses: pnpm/setup@v2
        with:
          runtime: node@26
          cache: true

      - name: Build site
        run: |
          pnpm build
          pnpm run postprocess

      - name: Deploy to Cloudflare Workers
        id: deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageManager: pnpm
          command: deploy
